// import house images
import bookedHouse from "../../public/assets/img/houses/bookedHouse.png";
import Room1 from "../../public/assets/img/houses/room1/room-1.png";
import Room2 from "../../public/assets/img/houses/room-2.png";
import Room3 from "../../public/assets/img/houses/room3.png";
// import House1 from "../../public/assets/img/houses/house1.png";

// Room 1 more images
import room1Tv from "../../public/assets/img/houses/room1/room1tv.png";
import room1Toilet from "../../public/assets/img/houses/room1/room1toilet.png";

// import house large images
import Room1Lg from "../../public/assets/img/houses/room1/room1lg2.png";
import Room2Lg from "../../public/assets/img/houses/room2lg2.png";
import Room3Lg from "../../public/assets/img/houses/room3lg.png";

// common images
import Kitchen from "../../public/assets/img/houses/common-rooms/kitchenlg.png";
import Laundry from "../../public/assets/img/houses/common-rooms/laundryKitchen.png";
import Stove from "../../public/assets/img/houses/common-rooms/stove.png";
import SeatingArea from "../../public/assets/img/houses/common-rooms/seatingSpace.png";

// import apartments images
import Apartment1 from "../../public/assets/img/apartments/a1.png";
// import apartments large images
import Apartment1Lg from "../../public/assets/img/apartments/a1lg.png";

// import agents images
import Agent1 from "../../public/assets/img/agents/agent1.png";
import Agent2 from "../../public/assets/img/agents/agent2.png";

export const housesData = [
    {
        id: 1,
        type: "Room",
        roomNumber: "1",
        name: "Newland Room 1",
        description:
            "Our Self-catering room with a double bed is the perfect choice for those looking for a comfortable and convenient way to explore the area. The room is spacious and well-appointed, featuring a comfortable double-sized bed with plush linens and pillows to ensure a great night's sleep. The room also includes a kitchenette that is fully equipped with all the necessary appliances and utensils to prepare your own meals.| The room is decorated in a modern style, with neutral colors, and natural light that comes through the window. Guests will also have access to a private bathroom, complete with a shower and all the necessary toiletries. The room is also equipped with a TV and free Wi-Fi to ensure that you stay connected during your stay. | The BnB is located in a quiet, residential area, and our guests will have access to a garden and outdoor seating area where you can enjoy the fresh air and beautiful views. Guests will also have access to on-site parking for their vehicles. | Whether you're visiting for business or pleasure, our Self-catering room with a double bed is the perfect choice for a comfortable and convenient stay. Book your stay today and experience the best that our area has to offer!",
        image: Room1,
        imageLg: Room1Lg,
        moreImages: {
            toilet: room1Toilet,
            tv: room1Tv,
            fridge: "",
            cupboard: "",
            kitchen: Kitchen,
            stove: Stove,
            laundry: Laundry,
            seatingSpace: SeatingArea,
        },
        area: "Menlyn / Newlands",
        address: "369 sandlewood Drive Newlands",
        bedrooms: "1",
        bathrooms: "",
        shower: "1",
        surface: "18",
        year: "2022",
        duration: "per night",
        price: "390",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
        },
        booked: false,
    },
    {
        id: 2,
        type: "Room",
        roomNumber: "2",
        name: "Newland Room 2",
        description:
            "Our Self-catering room with a double bed is the perfect choice for those looking for a comfortable and convenient way to explore the area. The room is spacious and well-appointed, featuring a comfortable double-sized bed with plush linens and pillows to ensure a great night's sleep. The room also includes a kitchenette that is fully equipped with all the necessary appliances and utensils to prepare your own meals.| The room is decorated in a modern style, with neutral colors, and natural light that comes through the window. Guests will also have access to a private bathroom, complete with a shower and all the necessary toiletries. The room is also equipped with a TV and free Wi-Fi to ensure that you stay connected during your stay. | The BnB is located in a quiet, residential area, and our guests will have access to a garden and outdoor seating area where you can enjoy the fresh air and beautiful views. Guests will also have access to on-site parking for their vehicles. | Whether you're visiting for business or pleasure, our Self-catering room with a double bed is the perfect choice for a comfortable and convenient stay. Book your stay today and experience the best that our area has to offer!",
        image: Room2,
        imageLg: Room2Lg,
        moreImages: {
            toilet: "",
            tv: "Hello",
            fridge: "",
            cupboard: "",
            kitchen: Kitchen,
            stove: Stove,
            laundry: Laundry,
            seatingSpace: SeatingArea,
        },
        area: "Menlyn / Newlands",
        address: "369 sandlewood Drive Newlands",
        bedrooms: "1",
        bathrooms: "0",
        shower: "1",
        surface: "18",
        year: "2020",
        duration: "per night",
        price: "390",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
        },
        booked: false,
    },
    {
        id: 3,
        type: "Room",
        roomNumber: "3",
        name: "Newland Room 3",
        description:
            "Our Self-catering room with a double bed is the perfect choice for those looking for a comfortable and convenient way to explore the area. The room is spacious and well-appointed, featuring a comfortable double-sized bed with plush linens and pillows to ensure a great night's sleep. The room also includes a kitchenette that is fully equipped with all the necessary appliances and utensils to prepare your own meals.| The room is decorated in a modern style, with neutral colors, and natural light that comes through the window. Guests will also have access to a private bathroom, complete with a shower and all the necessary toiletries. The room is also equipped with a TV and free Wi-Fi to ensure that you stay connected during your stay. | The BnB is located in a quiet, residential area, and our guests will have access to a garden and outdoor seating area where you can enjoy the fresh air and beautiful views. Guests will also have access to on-site parking for their vehicles. | Whether you're visiting for business or pleasure, our Self-catering room with a double bed is the perfect choice for a comfortable and convenient stay. Book your stay today and experience the best that our area has to offer!",
        image: Room3,
        imageLg: Room3Lg,
        moreImages: {
            toilet: "",
            tv: "Hello",
            fridge: "",
            cupboard: "",
            kitchen: "",
            stove: "",
            laundry: Laundry,
            seatingSpace: "",
        },
        imgPlaceholder: bookedHouse,
        area: "Menlyn / Newlands",
        address: "369 sandlewood Drive Newlands",
        bedrooms: "1",
        bathrooms: "",
        shower: "1",
        surface: "18",
        year: "2020",
        duration: "per night",
        price: "390",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
            whatsApp: "078 2455 785",
        },
        booked: true,
    },
    {
        id: 4,
        type: "Room",
        roomNumber: "4",
        name: "Newland Room 4",
        description:
            "Our Self-catering room with a Queen bed is the perfect choice for those looking for a comfortable and convenient way to explore the area. The room is spacious and well-appointed, featuring a comfortable double-sized bed with plush linens and pillows to ensure a great night's sleep. The room also includes a kitchenette that is fully equipped with all the necessary appliances and utensils to prepare your own meals.| The room is decorated in a modern style, with neutral colors, and natural light that comes through the window. Guests will also have access to a private bathroom, complete with a shower and all the necessary toiletries. The room is also equipped with a TV and free Wi-Fi to ensure that you stay connected during your stay. | The BnB is located in a quiet, residential area, and our guests will have access to a garden and outdoor seating area where you can enjoy the fresh air and beautiful views. Guests will also have access to on-site parking for their vehicles. | Whether you're visiting for business or pleasure, our Self-catering room with a double bed is the perfect choice for a comfortable and convenient stay. Book your stay today and experience the best that our area has to offer!",
        image: "",
        imageLg: "",
        moreImages: {
            toilet: "",
            tv: "Hello",
            fridge: "",
            cupboard: "",
            kitchen: "",
            stove: "",
            laundry: Laundry,
            seatingSpace: "",
        },
        imgPlaceholder: bookedHouse,
        area: "Menlyn / Newlands",
        address: "369 sandlewood Drive Newlands",
        bedrooms: "1",
        bathrooms: "",
        shower: "1",
        surface: "25",
        year: "2020",
        duration: "per night",
        price: "550",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
            whatsApp: "078 2455 785",
        },
        booked: true,
    },
    {
        id: 5,
        type: "Room",
        roomNumber: "5",
        name: "Newland Room 5",
        description:
            "Our Self-catering room with a Queen bed is the perfect choice for those looking for a comfortable and convenient way to explore the area. The room is spacious and well-appointed, featuring a comfortable double-sized bed with plush linens and pillows to ensure a great night's sleep. The room also includes a kitchenette that is fully equipped with all the necessary appliances and utensils to prepare your own meals.| The room is decorated in a modern style, with neutral colors, and natural light that comes through the window. Guests will also have access to a private bathroom, complete with a shower and all the necessary toiletries. The room is also equipped with a TV and free Wi-Fi to ensure that you stay connected during your stay. | The BnB is located in a quiet, residential area, and our guests will have access to a garden and outdoor seating area where you can enjoy the fresh air and beautiful views. Guests will also have access to on-site parking for their vehicles. | Whether you're visiting for business or pleasure, our Self-catering room with a double bed is the perfect choice for a comfortable and convenient stay. Book your stay today and experience the best that our area has to offer!",
        image: "",
        imageLg: "",
        moreImages: {
            toilet: "",
            tv: "Hello",
            fridge: "",
            cupboard: "",
            kitchen: "",
            stove: "",
            laundry: Laundry,
            seatingSpace: "",
        },
        imgPlaceholder: bookedHouse,
        area: "Menlyn / Newlands",
        address: "369 sandlewood Drive Newlands",
        bedrooms: "1",
        bathrooms: "",
        shower: "1",
        surface: "20",
        year: "2022",
        duration: "per night",
        price: "450",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
            whatsApp: "078 2455 785",
        },
        booked: true,
    },
    {
        id: 6,
        type: "Room",
        roomNumber: "6",
        name: "Newland Room 6",
        description:
            "Our Self-catering room with a Queen bed is the perfect choice for those looking for a comfortable and convenient way to explore the area. The room is spacious and well-appointed, featuring a comfortable double-sized bed with plush linens and pillows to ensure a great night's sleep. The room also includes a kitchenette that is fully equipped with all the necessary appliances and utensils to prepare your own meals.| The room is decorated in a modern style, with neutral colors, and natural light that comes through the window. Guests will also have access to a private bathroom, complete with a shower and all the necessary toiletries. The room is also equipped with a TV and free Wi-Fi to ensure that you stay connected during your stay. | The BnB is located in a quiet, residential area, and our guests will have access to a garden and outdoor seating area where you can enjoy the fresh air and beautiful views. Guests will also have access to on-site parking for their vehicles. | Whether you're visiting for business or pleasure, our Self-catering room with a double bed is the perfect choice for a comfortable and convenient stay. Book your stay today and experience the best that our area has to offer!",
        image: "",
        imageLg: "",
        moreImages: {
            toilet: "",
            tv: "Hello",
            fridge: "",
            cupboard: "",
            kitchen: "",
            stove: "",
            laundry: Laundry,
            seatingSpace: "",
        },
        imgPlaceholder: bookedHouse,
        area: "Menlyn / Newlands",
        address: "369 sandlewood Drive Newlands",
        bedrooms: "1",
        bathrooms: "",
        shower: "1",
        surface: "30",
        year: "2022",
        duration: "per night",
        price: "650",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
            whatsApp: "078 2455 785",
        },
        booked: true,
    },
    {
        id: 7,
        type: "Room",
        roomNumber: "7",
        name: "Room 7",
        description:
            "Our Self-catering room with a Queen bed is the perfect choice for those looking for a comfortable and convenient way to explore the area. The room is spacious and well-appointed, featuring a comfortable double-sized bed with plush linens and pillows to ensure a great night's sleep. The room also includes a kitchenette that is fully equipped with all the necessary appliances and utensils to prepare your own meals.| The room is decorated in a modern style, with neutral colors, and natural light that comes through the window. Guests will also have access to a private bathroom, complete with a shower and all the necessary toiletries. The room is also equipped with a TV and free Wi-Fi to ensure that you stay connected during your stay. | The BnB is located in a quiet, residential area, and our guests will have access to a garden and outdoor seating area where you can enjoy the fresh air and beautiful views. Guests will also have access to on-site parking for their vehicles. | Whether you're visiting for business or pleasure, our Self-catering room with a double bed is the perfect choice for a comfortable and convenient stay. Book your stay today and experience the best that our area has to offer!",
        image: "",
        imageLg: "",
        moreImages: {
            toilet: "",
            tv: "Hello",
            fridge: "",
            cupboard: "",
            kitchen: "",
            stove: "",
            laundry: Laundry,
            seatingSpace: "",
        },
        imgPlaceholder: bookedHouse,
        area: "Menlyn / Newlands",
        address: "369 sandlewood Drive Newlands",
        bedrooms: "1",
        bathrooms: "",
        shower: "1",
        surface: "18",
        year: "2022",
        duration: "per night",
        price: "390",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
            whatsApp: "078 2455 785",
        },
        booked: true,
    },
    {
        id: 8,
        type: "Room",
        roomNumber: "8",
        name: "Room 8",
        description:
            "Our Self-catering room with a Doble bed is the perfect choice for those looking for a comfortable and convenient way to explore the area. The room is spacious and well-appointed, featuring a comfortable double-sized bed with plush linens and pillows to ensure a great night's sleep. The room also includes a kitchenette that is fully equipped with all the necessary appliances and utensils to prepare your own meals.| The room is decorated in a modern style, with neutral colors, and natural light that comes through the window. Guests will also have access to a private bathroom, complete with a shower and all the necessary toiletries. The room is also equipped with a TV and free Wi-Fi to ensure that you stay connected during your stay. | The BnB is located in a quiet, residential area, and our guests will have access to a garden and outdoor seating area where you can enjoy the fresh air and beautiful views. Guests will also have access to on-site parking for their vehicles. | Whether you're visiting for business or pleasure, our Self-catering room with a double bed is the perfect choice for a comfortable and convenient stay. Book your stay today and experience the best that our area has to offer!",
        image: "",
        imgPlaceholder: bookedHouse,
        imageLg: "",
        moreImages: {
            toilet: "",
            tv: "Hello",
            fridge: "",
            cupboard: "",
            kitchen: "",
            stove: "",
            laundry: Laundry,
            seatingSpace: "",
        },
        area: "Menlyn / Newlands",
        address: "369 sandlewood Drive Newlands",
        bedrooms: "1",
        bathrooms: "",
        Shower: "1",
        surface: "20",
        year: "2022",
        duration: "per night",
        price: "390",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
        },
        booked: true,
    },
    {
        id: 9,
        type: "Apartament",
        roomNumber: "1",
        name: "Apartament 1 Monument Park",
        description:
            "This charming 2 bedroom guest house is ideal for those seeking a comfortable stay. The kitchen and seating room provide a convenient and inviting space for cooking and relaxing, with all necessary amenities. The two bedrooms are tastefully decorated and offer a peaceful retreat for a good night's sleep. The attached bathroom is modern and clean, with all essentials provided for your comfort. This guest house is in a prime location, making it easy to explore the surrounding area. Book now for a delightful and memorable stay!",
        image: "",
        imageLg: "",
        moreImages: {
            toilet: "",
            tv: "Hello",
            fridge: "",
            cupboard: "",
            kitchen: "",
            stove: "",
            laundry: Laundry,
            seatingSpace: "",
        },
        imgPlaceholder: bookedHouse,
        area: "Monument Park",
        address: "45 Bush buckLane",
        bedrooms: "2",
        bathrooms: "",
        shower: "1",
        surface: "96",
        year: "2022",
        duration: "per night",
        price: "1200",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
        },
        booked: true,
    },
    {
        id: 10,
        type: "Bachelor",
        roomNumber: "2",
        name: "Bachelor 2 Monument park ",
        description:
            "This bachelor apartment features a compact kitchen with essential appliances, a functional bathroom, a TV for entertainment, and free high-speed internet via Wi-Fi. Ideal for a single person seeking a low-maintenance, comfortable living space.",
        image: "",
        imageLg: "",
        moreImages: {
            toilet: "",
            tv: "Hello",
            fridge: "",
            cupboard: "",
            kitchen: "",
            stove: "",
            laundry: Laundry,
            seatingSpace: "",
        },
        imgPlaceholder: bookedHouse,
        area: "Monument Park",
        address: "45 Bushbuck Lane",
        bedrooms: "0.5",
        bathrooms: "",
        shower: "1",
        surface: "25",
        year: "2020",
        duration: "per night",
        price: "620",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
        },
        booked: true,
    },
    {
        id: 11,
        type: "Bachelor",
        roomNumber: "3",
        name: "Bachelor 3 Monument Park",
        description:
            "This bachelor apartment features a compact kitchen with essential appliances, a functional bathroom, a TV for entertainment, and free high-speed internet via Wi-Fi. Ideal for a single person seeking a low-maintenance, comfortable living space.",
        image: "",
        imageLg: "",
        moreImages: {
            toilet: "",
            tv: "Hello",
            fridge: "",
            cupboard: "",
            kitchen: "",
            stove: "",
            laundry: Laundry,
            seatingSpace: "",
        },
        imgPlaceholder: bookedHouse,
        area: "Monument Park",
        address: "45 Bushbuck Lane",
        bedrooms: "2",
        bathrooms: "1",
        shower: "1",
        surface: "20",
        year: "2022",
        duration: "per night",
        price: "620",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
        },
        booked: true,
    },
    {
        id: 12,
        type: "Room",
        roomNumber: "1",
        name: "Room 1 Pretoria west",
        description: "",
        image: "",
        imageLg: "",
        moreImages: {
            toilet: "",
            tv: "Hello",
            fridge: "",
            cupboard: "",
            kitchen: "",
            stove: "",
            laundry: Laundry,
            seatingSpace: "",
        },
        imgPlaceholder: bookedHouse,
        area: "Pretoria west",
        address: "Pretoria west",
        bedrooms: "1",
        bathrooms: "1",
        surface: "4600 sq ft",
        year: "2022",
        duration: "per night",
        price: "320",
        agent: {
            image: Agent2,
            name: "Fatuma",
            phone: "072 42 2600",
        },
        booked: true,
    },
];
